### ISSUE TITLE
Starting ydl.Download() causing windows forms to recreate a new window.

### ISSUE THREAD

**Issue by dondish** [BrianAllred/NYoutubeDL#15] opened 2018-05-08 13:47 UTC
I really don't know why but every time I try to do the Download method it opens another window.

Steps to reproduce: create a simple windows forms app and start a Download

I appreciate if you can help me make it stay in the same form window.

**Comment by BrianAllred** [comment] 2018-05-24 21:33
I created a super simple Forms app and couldn't reproduce this. Can you provide a code snippet?

![image](https://user-images.githubusercontent.com/5847511/40514772-1084a71e-5f70-11e8-825f-89d0e34d5dc1.png)

```csharp
namespace WindowsFormsApp1
{
    using System;
    using System.Windows.Forms;
    using NYoutubeDL;

    public partial class Form1 : Form
    {
        private readonly YoutubeDL ydlClient = new YoutubeDL();

        public Form1()
        {
            InitializeComponent();
        }

        private void Button1Click(object sender, EventArgs e)
        {
            this.ydlClient.VideoUrl = "https://www.youtube.com/watch?v=vhgp_WId5ds";
            this.ydlClient.Download(true);
        }
    }
}
```

**Comment by dondish** [comment] 2018-05-25 05:18
The problem is with event registering. Try to put the current information in a label.

**Comment by BrianAllred** [comment] 2018-05-25 15:36
Same thing.

![image](https://user-images.githubusercontent.com/5847511/40553137-62b3cac8-6007-11e8-89ca-fa695f94c571.png)

![image](https://user-images.githubusercontent.com/5847511/40553160-6f939a3e-6007-11e8-9798-2fc8d8a5fd7b.png)

```csharp
namespace WindowsFormsApp1
{
    #region Using

    using System;
    using System.Windows.Forms;
    using NYoutubeDL;
    using NYoutubeDL.Models;

    #endregion

    public partial class Form1 : Form
    {
        private readonly YoutubeDL ydlClient = new YoutubeDL();

        public Form1()
        {
            this.InitializeComponent();
        }

        private void Button1Click(object sender, EventArgs e)
        {
            this.ydlClient.VideoUrl = "https://www.youtube.com/watch?v=vhgp_WId5ds";
            this.ydlClient.PrepareDownload();

            this.ydlClient.Info.PropertyChanged += (o, args) =>
            {
                VideoDownloadInfo info = (VideoDownloadInfo) o;
                this.Invoke(new MethodInvoker(delegate
                {
                    this.label1.Text = info.Title;
                }));
            };

            this.ydlClient.Download();
        }
    }
}
```

**Comment by BrianAllred** [comment] 2018-06-04 01:21
Closing this due to project migration. Please follow up at https://gitlab.com/BrianAllred/NYoutubeDL/issues/15.

**Closed as completed by BrianAllred** 2018-06-04 01:21 UTC
